### ISSUE TITLE
Consistently validate data with a missing or incorrect version against OCDS 1.1

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/lib-cove-ocds#110]
Whilst testing https://github.com/open-contracting/cove-ocds/issues/165 I noticed that if the `version` key is omitted from the package metadata then the DRT validates the data against OCDS version 1.0, but if the `version` key is present and populated with a number rather than a string then the DRT validates the data against OCDS version 1.1.

I would expect the DRT to default to validating against the same version of the schema. Most publishers publish OCDS 1.1 so I think that should be the default.

Here's some minimal example to reproduce the issue:

```json
{
  "version": 1.1,
  "releases": []
}
```

```json
{
  "releases": []
}
```

**Comment by jpmckinney** [comment]
Noting that a missing `version` is the way to identify OCDS 1.0 data.

If a `version` key is present (even if invalid), an attempt to publish 1.1 is assumed.

However, at this point, probably best to just assume the user was attempting to publish 1.1 data, if `version` missing.
