### ISSUE TITLE
Closed codelist errors appear in both 'validation errors' and 'codelist validation errors'

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/lib-cove-ocds#115]
For example, the error with the procurementMethod codelist appears twice:

![image](https://user-images.githubusercontent.com/19265814/43996700-353c7eb0-9d96-11e8-8e8b-9f5d8c3903ac.png)

Could we get add the additional information which appears in the 'validation errors' section (the error count and location of first 3 errors) to the information in the 'codelist validation errors' section and just show the error in the codelist section?

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Closed codelist errors appear in both 'validation errors' and 'codelist validation errors'](https://trello.com/c/kzatVkpg/42-closed-codelist-errors-appear-in-both-validation-errors-and-codelist-validation-errors)

**Comment by romifz** [comment]
I guess some action has been taken regarding this issue, because closed codelist errors don't appear anymore as validation errors ([example here](https://pastebin.com/raw/HyRnqKPn)).

However, wouldn't be best to keep closed codelist errors inside the `validation_errors` list, as they are breaking structural rules of the schema? I see that the Data Review Tool shows these as check failures, but when using JSON cove output in Kingfisher I would expect to find all structural errors in a single place.

**Comment by jpmckinney** [comment]
Agreed that it would be better to have codelist errors in validation_errors. However, tools expect these errors in additional_closed_codelist_values, so they are left there.

**Comment by jpmckinney** [comment]
Actually, closed codelists errors DO appear in both - it just has to be a closed codelist that is also an array, like `tag` in OCDS 1.1.

Extensions with arrays using closed codelists are:

* selectionCriteria `appliesTo`
* participationFee `type`
* bid `countriesOfOrigin`

CoVE had a commit at https://github.com/OpenDataServices/cove/commit/b0591da69cae8258c7029d11e22297d86e6b98c3 to set `isCodelist` on the `items` property, such that `get_schema_validation_errors` would skip over the enum error. However, a bug introduced in OpenDataServices/lib-cove@011a2bd meant that the setting of `isCodelist` no longer occurred.

In lib-cove-ocds as it is now, we don't run any of that code – which is way too "spooky action at a distance" by OCP standards. We can instead modify the schema in the `get_schema_obj` function to add `isCodelist` and reuse the existing code in `get_schema_validation_errors`

**Comment by jpmckinney** [comment]
Test data

String closed codelist:

`{"version":"1.1","releases":[{"tender":{"procurementMethod":"bad"}}]}`

`{"version":"1.1","records":[{"releases":[{"id":"1","tender":{"procurementMethod":"bad"}}]}]}`

Array closed codelist:

`{"version":"1.1","releases":[{"tag":["bad"]}]}`

`{"version":"1.1","records":[{"releases":[{"id":"1","tag":["bad"]}]}]}`
