### ISSUE TITLE
Add general tests

### ISSUE THREAD

**Issue by ghost** [open-contracting/lib-cove-ocds#24]
In Cove, we used to have "secret tests". We removed these for various reasons - see https://github.com/OpenDataServices/cove/issues/1192

However, it would be good to have "general" tests. These tests should be 

- Public to avoid some of the issues with secret tests (only some staff can work on the code, etc)
- Use real data, some good and some bad in some way
- Check the whole output of lib-cove-ocds, rather than very specific checks that are done in other tests that are designed to check very specific functionality
- Documented, so we are clear what to expect from each bit of test data

These tests will not replace other tests that are designed to check very specific functionality, but rather will provide a final rough check intended to prevent any unexpected changes.

With general tests like this, it can be hard to when they fail if changes are intended or not. With clearer documentation we hope to help this issue.

The sample data should probably be stored in a separate repository. This data may get very large, and also having it in a separate repository makes it easier to redact later if we ever realise we need to. (I think there are existing repos with data that may do this job?)

ps. Related to https://github.com/OpenDataServices/flatten-tool/issues/320

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add general tests to LIb Cove OCDS](https://trello.com/c/T3vKZahj/63-add-general-tests-to-lib-cove-ocds)

**Comment by jpmckinney** [comment]
Coverage is currently 78% https://coveralls.io/github/open-contracting/lib-cove-ocds?branch=master It'd be good to get over 90%; otherwise, refactoring and changes are fairly high-risk of introducing bugs.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve automated testing of the DRT](https://trello.com/c/HqW5Nrsc/50-improve-automated-testing-of-the-drt)

**Comment by jpmckinney** [comment]
Merging with #52
