### ISSUE TITLE
Documents Section: Include counts of unique document IDs

### ISSUE THREAD

**Issue by robredpath** [open-contracting/lib-cove-ocds#71]
Feature request from https://github.com/OpenDataServices/cove/issues/263 

> When a file containing multiple releases is validated, the total count of items and documents are shown. For clarity, could we also include the unique count of:
>
> *  documents based on id
>
> By showing that we found 19 mentions of a document and 4 unique document ids, publishers can be check the release has been validated correctly.

**Comment by jpmckinney** [comment]
KFI is planned for removal in the updated frontend, so this issue is no longer applicable.
