### ISSUE TITLE
Flags all fields in records/compiledRelease as additional

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/lib-cove-ocds#84]
inally reported by @duncandewhurst at https://github.com/OpenDataServices/cove/issues/1232

Tested with the [record](https://standard.open-contracting.org/review/data/2cbdeed2-351a-4a77-b0dd-76dbeb4bca0f) from the sample data repo:

![image](https://user-images.githubusercontent.com/19265814/65695467-86daf900-e06f-11e9-8352-52c011a8b772.png)

**Comment by jpmckinney** [comment]
Like #61 and #68, the easiest option might just be to not report additional fields on compiled releases.

**Comment by duncandewhurst** [comment]
Many publishers only publish compiled releases and once https://github.com/open-contracting/standard/issues/1092 is done it will be possible for publishers to publish a record package that only contains a compiled release, so I don't think we should not report additional fields on compiled releases.

**Comment by jpmckinney** [comment]
Might have been fixed? http://standard.open-contracting.org/review/?source_url=https://raw.githubusercontent.com/open-contracting/sample-data/main/fictional-example/1.1/record/ocds-213czf-000-00001.json

**Comment by duncandewhurst** [comment]
Seems like it!
