### ISSUE TITLE
Improve usability of JSON output

### ISSUE THREAD

**Issue by pindec** [open-contracting/lib-cove-ocds#85]
From discussion in cove-ocds [#59](https://github.com/open-contracting/cove-ocds/issues/59#issuecomment-707640835):

The output of lib-cove-ocds could be improved to support publishers wanting to use it & ocdskit-validate directly to validate large amounts of data and/or use in production pipelines (as opposed to DRT for rapid sample data dev). 

ocdskit-validate output doesn't seem to give the same locations info as DRT, and lib-cove-ocds output may need some processing to make it more user-friendly.

**Comment by jpmckinney** [comment]
I think we can focus on improving the documentation. In #87 we added this to the readme, which makes the JSON output much easier to interpret: https://github.com/open-contracting/lib-cove-ocds#output-json-format

Potential improvements to the documentation might include sample code (or a notebook) that processes the JSON output into whatever format the user desires.

It would take a fair bit of discovery work to determine a more use-friendly format, and it's quite possible that different publishers want different reports.

We're not presently aware of publishers using lib-cove-ocds directly, so I will close this issue for now, though it can be re-opened and re-titled to be about documentation improvements if there is new demand.
