### ISSUE TITLE
Remove `ocds_prefixes_bad_format` at top level

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/lib-cove-ocds#94]
It should be removed in favour of `conformance_errors/ocds_prefixes_bad_format`.

Spotted while documenting output JSON format https://github.com/open-contracting/lib-cove-ocds/pull/93

**Comment by jpmckinney** [comment]
The top-level was introduced in https://github.com/OpenDataServices/cove/commit/33e8372e81da5a21cd7ae0d6ef93b04185c3edb3

Part of the code moved to `conformance_errors`, but the original top-level lines were left behind: https://github.com/OpenDataServices/cove/commit/c050181a45ef8ba2f1b94a21b246201749a7707c
